- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: add a text file
      ansible.builtin.command: echo "testing" >> /home/ubuntu/text.txt

